fix for "AttributeError: Values instance has no attribute 'jpegquality'": when the system does not have PIL (aka python-imaging) the client errored out because the jpeg options were unset, we now set them to default values
git-svn-id: https://xpra.org/svn/Xpra@262 3bb7dfac-3a0b-4e04-842a-767bc560f471